//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalTimeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalTimeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the date fields is not in the correct format..
        /// </summary>
        internal static string ErrStrBadDateFormat {
            get {
                return ResourceManager.GetString("ErrStrBadDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Not Valid.
        /// </summary>
        internal static string ErrStrBadFormatTitle {
            get {
                return ResourceManager.GetString("ErrStrBadFormatTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LeftArrowBtn {
            get {
                object obj = ResourceManager.GetObject("LeftArrowBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrintBtn {
            get {
                object obj = ResourceManager.GetObject("PrintBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon PTT_Active_Icon {
            get {
                object obj = ResourceManager.GetObject("PTT_Active_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PTT_Main_Icon {
            get {
                object obj = ResourceManager.GetObject("PTT_Main_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PTT_Paused_Icon {
            get {
                object obj = ResourceManager.GetObject("PTT_Paused_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RefreshPageBtn {
            get {
                object obj = ResourceManager.GetObject("RefreshPageBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ReportStrActivity {
            get {
                return ResourceManager.GetString("ReportStrActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} from {2} to {3}. Duration {4}({5}) {6}.
        /// </summary>
        internal static string ReportStrActivityLine {
            get {
                return ResourceManager.GetString("ReportStrActivityLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity from {0} to {1}.
        /// </summary>
        internal static string ReportStrActivityTitle {
            get {
                return ResourceManager.GetString("ReportStrActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity with details.
        /// </summary>
        internal static string ReportStrActivityWithTasks {
            get {
                return ResourceManager.GetString("ReportStrActivityWithTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity with Tasks from {0} to {1}.
        /// </summary>
        internal static string ReportStrActivityWithTasksTitle {
            get {
                return ResourceManager.GetString("ReportStrActivityWithTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable.
        /// </summary>
        internal static string ReportStrBillableColHeader {
            get {
                return ResourceManager.GetString("ReportStrBillableColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string ReportStrCustomerColHeader {
            get {
                return ResourceManager.GetString("ReportStrCustomerColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ReportStrDayHeader {
            get {
                return ResourceManager.GetString("ReportStrDayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activity.
        /// </summary>
        internal static string ReportStrNoActivity {
            get {
                return ResourceManager.GetString("ReportStrNoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Billable.
        /// </summary>
        internal static string ReportStrNonBillableColHeader {
            get {
                return ResourceManager.GetString("ReportStrNonBillableColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not billable.
        /// </summary>
        internal static string ReportStrNotBillableReportTag {
            get {
                return ResourceManager.GetString("ReportStrNotBillableReportTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string ReportStrSummary {
            get {
                return ResourceManager.GetString("ReportStrSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary from {0} to {1}.
        /// </summary>
        internal static string ReportStrSummaryTitle {
            get {
                return ResourceManager.GetString("ReportStrSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary with tasks.
        /// </summary>
        internal static string ReportStrSummaryWithTasks {
            get {
                return ResourceManager.GetString("ReportStrSummaryWithTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary with Tasks from {0} to {1}.
        /// </summary>
        internal static string ReportStrSummaryWithTasksTitle {
            get {
                return ResourceManager.GetString("ReportStrSummaryWithTasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string ReportStrTaskColHeader {
            get {
                return ResourceManager.GetString("ReportStrTaskColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}).
        /// </summary>
        internal static string ReportStrTimeFormat {
            get {
                return ResourceManager.GetString("ReportStrTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ReportStrTotalColHeader {
            get {
                return ResourceManager.GetString("ReportStrTotalColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ReportStrTotalTitle {
            get {
                return ResourceManager.GetString("ReportStrTotalTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RightArrowBtn {
            get {
                object obj = ResourceManager.GetObject("RightArrowBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkipEmptyBtn {
            get {
                object obj = ResourceManager.GetObject("SkipEmptyBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Time Tracker.
        /// </summary>
        internal static string StrAppTitle {
            get {
                return ResourceManager.GetString("StrAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} for {2}.
        /// </summary>
        internal static string StrAppTitleWithTaskInfo {
            get {
                return ResourceManager.GetString("StrAppTitleWithTaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1}.
        /// </summary>
        internal static string StrMruMenuText {
            get {
                return ResourceManager.GetString("StrMruMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;None&gt;.
        /// </summary>
        internal static string StrNoneInBrackets {
            get {
                return ResourceManager.GetString("StrNoneInBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string StrPageY {
            get {
                return ResourceManager.GetString("StrPageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string StrPageYOfZ {
            get {
                return ResourceManager.GetString("StrPageYOfZ", resourceCulture);
            }
        }
    }
}
